#!/usr/bin/env node
// Extracts the 32x32 1-bit piece sprites from the original nand2tetris
// SpriteSheet.jack and writes them to src/sprites/data.ts.
//
// Usage: node scripts/extract-sprites.mjs path/to/SpriteSheet.jack
//
// Jack sprite layout (see Game.draw_sprite in the original): 64 words, where
//   [0..15]  = rows 0..15,  left 16px
//   [16..31] = rows 0..15,  right 16px
//   [32..47] = rows 16..31, left 16px
//   [48..63] = rows 16..31, right 16px
// Within a word, bit 0 is the leftmost pixel and 1 = black.

import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';

const src = process.argv[2];
if (!src) {
  console.error('usage: extract-sprites.mjs path/to/SpriteSheet.jack');
  process.exit(1);
}

const text = readFileSync(src, 'utf8');
const arrays = {};
for (const [, name, idx, val] of text.matchAll(/let (\w+)\[(\d+)\]\s*=\s*(-?\d+)\s*;/g)) {
  (arrays[name] ??= new Array(64).fill(0))[Number(idx)] = Number(val);
}

function toRows(words) {
  const rows = [];
  for (let r = 0; r < 32; r++) {
    const base = r < 16 ? r : r - 16 + 32;
    let line = '';
    for (const w of [words[base] & 0xffff, words[base + 16] & 0xffff]) {
      for (let b = 0; b < 16; b++) line += (w >> b) & 1 ? '1' : '0';
    }
    rows.push(line);
  }
  return rows;
}

// The original has a hand-drawn sprite per (piece colour, kind, square
// colour): e.g. WNW = white knight on a white square, WNB = on a black square.
// Only the light-square variants are kept; the renderer derives a transparent
// background from them (see src/sprites/render.ts), so pieces read the same on
// any square colour.
const kinds = ['P', 'N', 'B', 'R', 'Q', 'K'];
const out = {};
for (const colour of ['W', 'B']) {
  for (const kind of kinds) {
    const name = `${colour}${kind}W`;
    if (!arrays[name]) throw new Error(`sprite ${name} not found`);
    // A few sprites have stray pixels on the outermost ring; clear it so the
    // background flood fill starts from a clean edge.
    let rows = toRows(arrays[name]).map((row, r) =>
      r === 0 || r === 31 ? '0'.repeat(32) : '0' + row.slice(1, 31) + '0',
    );
    // The white queen is drawn symmetric except for two slips on its left
    // side (rows 6 and 25). Row 6 leaves the left orb and a crown spike open,
    // so the flood fill leaked in and showed them as transparent holes.
    // Mirror the right half onto the left, as in the black queen.
    if (name === 'WQW') {
      rows = rows.map((row) => [...row.slice(16)].reverse().join('') + row.slice(16));
    }
    // Each row as a 32-bit hex string keeps the generated file compact.
    out[`${colour.toLowerCase()}${kind}`] = rows.map((row) =>
      parseInt(row.split('').reverse().join(''), 2).toString(16).padStart(8, '0'),
    );
  }
}

const here = dirname(fileURLToPath(import.meta.url));
const dest = resolve(here, '../src/sprites/data.ts');
const body = Object.entries(out)
  .map(([k, rows]) => `  ${k}: [\n${rows.map((r) => `    '${r}',`).join('\n')}\n  ],`)
  .join('\n');
writeFileSync(
  dest,
  `// Generated by scripts/extract-sprites.mjs from the original SpriteSheet.jack.
// Each sprite is 32 rows; each row is a 32-bit hex number where bit 0 is the
// leftmost pixel and a set bit is a dark pixel.
export const SPRITES: Record<string, readonly string[]> = {
${body}
};
`,
);
console.log(`wrote ${Object.keys(out).length} sprites to ${dest}`);
